# Generated by Django 4.2.14 on 2025-02-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FetchedEmailData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_student', models.CharField(max_length=255)),
                ('jsn_iin', models.CharField(max_length=255)),
                ('payment_amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('payment_id_match', models.CharField(max_length=255)),
                ('is_payed', models.BooleanField(default=False)),
            ],
        ),
    ]
