version: '3.9'

services:
  app:
    build:
      context: .
    command: gunicorn --bind 0.0.0.0:8000 stud_test.wsgi:application
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/staticfiles
      - ./media:/app/media
    expose:
      - 8000
    # depends_on:
    #   - db
    env_file:
      - .env

  # db:
  #   image: postgres:13
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     POSTGRES_DB: ${DB_NAME}
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./media:/app/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app

volumes:
  postgres_data:
