# Generated by Django 4.2.14 on 2025-02-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='files', verbose_name='Excel ученики')),
            ],
            options={
                'verbose_name_plural': 'Список школьников',
            },
        ),
    ]
