# Generated by Django 4.2.14 on 2025-02-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttest',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Excel файл'),
        ),
    ]
